// Generated by CoffeeScript 1.10.0
(function() {
  window.Router = {
    route: function(hash) {
      if (hash === "" || (hash == null)) {
        hash = "#welcome";
      }
      switch (hash.split("/")[0]) {
        case "":
          window.location.href += hash;
          window.location.reload();
          break;
        case "#welcome":
          $("#view-main").load("welcome.html");
          break;
        case "#upload":
          $("#view-main").load("uploading.html");
          break;
        case "#timetable":
          $("#view-main").load("timetable.html");
          break;
        case "#step2":
          $("#view-main").load("step2.html");
      }
      return window.location.hash = hash;
    },
    routeTimetable: function() {
      var currentUser, hash;
      hash = window.location.hash.split("/");
      if (hash[0] === "#timetable" && (hash[1] != null)) {
        return currentUser = hash[1];
      }
    }
  };

}).call(this);

//# sourceMappingURL=Router.js.map
